# Generated by Django 2.2.17 on 2021-03-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gubookhub_app', '0002_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
