# Generated by Django 2.2.17 on 2021-03-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gubookhub_app', '0004_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='Default Course', unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(default='Default Course', unique=True),
        ),
    ]
