# Generated by Django 2.2.17 on 2021-03-22 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gubookhub_app', '0006_auto_20210322_2019'),
        ('gubookhub_app', '0006_auto_20210322_1951'),
    ]

    operations = [
    ]
